name: coverage
on: [push]
jobs:
  linux-coverage:
    name: linux
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Install ninja
        run: sudo apt-get install ninja-build

      - name: Configure
        run:  mkdir build && cd build && cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=toolchains/x86-linux-gcc-9.cmake -DCMAKE_BUILD_TYPE=Coverage ..

      - name: build
        run: cd build && ninja

      - name: Test
        run: cd build && ctest --output-on-failure

      - name: Upload report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          fail_ci_if_error: true
